import type { Country } from "./types";

/**
 * Every nation that gained independence from the British Empire, sorted by name.
 *
 * Transcribed from `british-empire-independence.csv` at the repo root, which stays
 * the research record of where each fact came from (every row carries a source URL).
 * Region and flag colours are not in the CSV and were authored alongside it.
 *
 * Read this through the helpers in `./queries` rather than importing it directly —
 * they own the lookups, groupings and sort orders the pages rely on.
 */
export const COUNTRIES: readonly Country[] = [
  {
    slug: "afghanistan",
    name: "Afghanistan",
    region: "asia",
    independence: { day: 19, month: 8, year: 1919, raw: "19 August 1919" },
    palette: {
      primary: "#007a36",
      secondary: "#d32011",
      flagStops: ["#000000", "#d32011", "#007a36"],
    },
    yearsOfBritishRule: 40,
    basisForStartDate: "British control of foreign policy from 1879",
    nameBeforeBritish: "Emirate of Afghanistan",
    splitUpAfterBritishLeft: "No - Durand Line already drawn in 1893",
    stillCommonwealthRealm: "No",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Yes - Third Anglo-Afghan War",
    sourceUrl: "https://en.wikipedia.org/wiki/Anglo-Afghan_Treaty_of_1919",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "antigua-and-barbuda",
    name: "Antigua and Barbuda",
    region: "caribbean",
    independence: { day: 1, month: 11, year: 1981, raw: "1 November 1981" },
    palette: {
      primary: "#0072c6",
      secondary: "#fcd116",
      flagStops: ["#ce1126", "#000000", "#0072c6", "#fcd116"],
    },
    yearsOfBritishRule: 349,
    basisForStartDate: "From English settlement, 1632",
    nameBeforeBritish: "Antigua, Leeward Islands",
    splitUpAfterBritishLeft: "Barbuda still seeking separation",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Barbuda objected to the union",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Antigua_and_Barbuda",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "australia",
    name: "Australia",
    region: "oceania",
    independence: { day: 1, month: 1, year: 1901, raw: "1 January 1901 (Statute of Westminster adopted 1942; Australia Act 1986)", note: "Statute of Westminster adopted 1942; Australia Act 1986" },
    palette: {
      primary: "#00247d",
      secondary: "#cf142b",
      flagStops: ["#00247d", "#ffffff", "#cf142b"],
    },
    yearsOfBritishRule: 113,
    basisForStartDate: "From first British settlement, 1788",
    nameBeforeBritish: "Six separate colonies",
    splitUpAfterBritishLeft: "No - six colonies federated",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes - federation held",
    violenceAtTransfer: "No at transfer (frontier wars against Aboriginal peoples were a separate matter)",
    sourceUrl: "https://en.wikipedia.org/wiki/Federation_of_Australia",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "bahrain",
    name: "Bahrain",
    region: "middle-east",
    independence: { day: 15, month: 8, year: 1971, raw: "15 August 1971" },
    palette: {
      primary: "#ce1126",
      secondary: "#8a0f1d",
      flagStops: ["#ffffff", "#ce1126"],
    },
    yearsOfBritishRule: 91,
    basisForStartDate: "From exclusive agreement, 1880",
    nameBeforeBritish: "British Protectorate of Bahrain",
    splitUpAfterBritishLeft: "Declined to join the UAE federation",
    stillCommonwealthRealm: "No - emirate, kingdom from 2002",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Bahrain",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "bangladesh",
    name: "Bangladesh",
    region: "asia",
    independence: { day: 16, month: 12, year: 1971, raw: "16 December 1971 (declared 26 March 1971)", note: "declared 26 March 1971" },
    palette: {
      primary: "#006a4e",
      secondary: "#f42a41",
      flagStops: ["#006a4e", "#f42a41", "#006a4e"],
    },
    yearsOfBritishRule: 190,
    basisForStartDate: "As part of British India",
    nameBeforeBritish: "East Bengal / East Pakistan",
    splitUpAfterBritishLeft: "Yes - seceded from Pakistan",
    stillCommonwealthRealm: "No - republic",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Yes - 300,000 to 3 million dead, ~10 million refugees",
    sourceUrl: "https://en.wikipedia.org/wiki/Bangladesh_Liberation_War",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "barbados",
    name: "Barbados",
    region: "caribbean",
    independence: { day: 30, month: 11, year: 1966, raw: "30 November 1966" },
    palette: {
      primary: "#00267f",
      secondary: "#ffc726",
      flagStops: ["#00267f", "#ffc726", "#00267f"],
    },
    yearsOfBritishRule: 339,
    basisForStartDate: "From English settlement, 1627 (unbroken)",
    nameBeforeBritish: "Colony of Barbados",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - became a republic 30 November 2021",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Barbados_Independence_Act_1966",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "belize",
    name: "Belize",
    region: "caribbean",
    independence: { day: 21, month: 9, year: 1981, raw: "21 September 1981" },
    palette: {
      primary: "#003f87",
      secondary: "#ce1126",
      flagStops: ["#003f87", "#ce1126", "#003f87"],
    },
    yearsOfBritishRule: 119,
    basisForStartDate: "From colony of British Honduras, 1862",
    nameBeforeBritish: "British Honduras (renamed 1973)",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No; British troops stayed until 1994 over the Guatemalan claim",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Belize",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "botswana",
    name: "Botswana",
    region: "africa",
    independence: { day: 30, month: 9, year: 1966, raw: "30 September 1966" },
    palette: {
      primary: "#75aadb",
      secondary: "#1b1d21",
      flagStops: ["#75aadb", "#ffffff", "#000000"],
    },
    yearsOfBritishRule: 81,
    basisForStartDate: "From protectorate, 1885",
    nameBeforeBritish: "Bechuanaland Protectorate",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic at independence",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Botswana_Independence_Act_1966",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "brunei",
    name: "Brunei",
    region: "asia",
    independence: { day: 1, month: 1, year: 1984, raw: "1 January 1984" },
    palette: {
      primary: "#fcd116",
      secondary: "#cf1126",
      flagStops: ["#fcd116", "#ffffff", "#000000", "#cf1126"],
    },
    yearsOfBritishRule: 96,
    basisForStartDate: "From protectorate, 1888",
    nameBeforeBritish: "Sultanate of Brunei",
    splitUpAfterBritishLeft: "Lost Sarawak and Sabah to the Brookes and the North Borneo Company earlier",
    stillCommonwealthRealm: "No - its own absolute monarchy",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "1962 Brunei Revolt crushed by British troops from Singapore",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Brunei",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "contested",
  },
  {
    slug: "canada",
    name: "Canada",
    region: "north-america",
    independence: { day: 1, month: 7, year: 1867, raw: "1 July 1867 (Statute of Westminster 1931; Canada Act 1982)", note: "Statute of Westminster 1931; Canada Act 1982" },
    palette: {
      primary: "#d80621",
      secondary: "#85091e",
      flagStops: ["#d80621", "#ffffff", "#d80621"],
    },
    yearsOfBritishRule: 104,
    basisForStartDate: "From cession of New France, 1763",
    nameBeforeBritish: "British North America",
    splitUpAfterBritishLeft: "No - provinces merged",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes - grew by accretion to 1949",
    violenceAtTransfer: "No - constitutional throughout",
    sourceUrl: "https://en.wikipedia.org/wiki/Canadian_Confederation",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "cyprus",
    name: "Cyprus",
    region: "europe",
    independence: { day: 16, month: 8, year: 1960, raw: "16 August 1960" },
    palette: {
      primary: "#d57800",
      secondary: "#4e5b31",
      flagStops: ["#ffffff", "#d57800", "#4e5b31"],
    },
    yearsOfBritishRule: 82,
    basisForStartDate: "From British administration, 1878",
    nameBeforeBritish: "British Cyprus (Ottoman before)",
    splitUpAfterBritishLeft: "Yes - de facto partitioned since 1974; UK kept two Sovereign Base Areas",
    stillCommonwealthRealm: "No - republic",
    unitedAfterIndependence: "No - bicommunal state broke down by 1963",
    violenceAtTransfer: "Yes - EOKA insurgency 1955-59 (~500 dead); 1974 Turkish invasion",
    sourceUrl: "https://en.wikipedia.org/wiki/Zurich_and_London_Agreement",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "dominica",
    name: "Dominica",
    region: "caribbean",
    independence: { day: 3, month: 11, year: 1978, raw: "3 November 1978" },
    palette: {
      primary: "#006b3f",
      secondary: "#d41c30",
      flagStops: ["#006b3f", "#fcd116", "#000000", "#d41c30"],
    },
    yearsOfBritishRule: 215,
    basisForStartDate: "From cession by France, 1763",
    nameBeforeBritish: "Dominica, Windward Islands",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic from day one",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Dominica",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "egypt",
    name: "Egypt",
    region: "africa",
    independence: { day: 28, month: 2, year: 1922, raw: "28 February 1922 (full withdrawal from Suez 1956)", note: "full withdrawal from Suez 1956" },
    palette: {
      primary: "#ce1126",
      secondary: "#c09300",
      flagStops: ["#ce1126", "#ffffff", "#000000"],
    },
    yearsOfBritishRule: 40,
    basisForStartDate: "From British occupation, 1882",
    nameBeforeBritish: "Sultanate of Egypt (Ottoman)",
    splitUpAfterBritishLeft: "Sudan separated in 1956",
    stillCommonwealthRealm: "No - republic 1953",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Yes - 1919 Revolution (~800 dead); Suez Crisis 1956",
    sourceUrl: "https://en.wikipedia.org/wiki/Unilateral_Declaration_of_Egyptian_Independence",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "eswatini",
    name: "Eswatini",
    region: "africa",
    independence: { day: 6, month: 9, year: 1968, raw: "6 September 1968" },
    palette: {
      primary: "#3e5eb9",
      secondary: "#ffd900",
      flagStops: ["#3e5eb9", "#ffd900", "#b10c0c"],
    },
    yearsOfBritishRule: 65,
    basisForStartDate: "From protectorate, 1903",
    nameBeforeBritish: "Swaziland (renamed Eswatini 2018)",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - its own absolute monarchy",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Swaziland_Independence_Act_1968",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "fiji",
    name: "Fiji",
    region: "oceania",
    independence: { day: 10, month: 10, year: 1970, raw: "10 October 1970" },
    palette: {
      primary: "#68bfe5",
      secondary: "#cf142b",
      flagStops: ["#68bfe5", "#ffffff", "#cf142b"],
    },
    yearsOfBritishRule: 96,
    basisForStartDate: "From cession by chiefs, 1874",
    nameBeforeBritish: "Colony of Fiji",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic 1987; realm 1970-87",
    unitedAfterIndependence: "iTaukei and Indo-Fijian split",
    violenceAtTransfer: "No at transfer; coups 1987, 2000, 2006",
    sourceUrl: "https://en.wikipedia.org/wiki/Fiji_Independence_Act_1970",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "ghana",
    name: "Ghana",
    region: "africa",
    independence: { day: 6, month: 3, year: 1957, raw: "6 March 1957" },
    palette: {
      primary: "#006b3f",
      secondary: "#fcd116",
      flagStops: ["#ce1126", "#fcd116", "#006b3f"],
    },
    yearsOfBritishRule: 83,
    basisForStartDate: "From Gold Coast colony, 1874",
    nameBeforeBritish: "Gold Coast and British Togoland",
    splitUpAfterBritishLeft: "No - gained territory, Togoland merged in",
    stillCommonwealthRealm: "No - republic 1960; realm 1957-60",
    unitedAfterIndependence: "Yes - four territories into one",
    violenceAtTransfer: "No at transfer; 1948 Accra riots preceded it",
    sourceUrl: "https://en.wikipedia.org/wiki/Ghana_Independence_Act_1957",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "grenada",
    name: "Grenada",
    region: "caribbean",
    independence: { day: 7, month: 2, year: 1974, raw: "7 February 1974" },
    palette: {
      primary: "#007a5e",
      secondary: "#fcd116",
      flagStops: ["#ce1126", "#fcd116", "#007a5e"],
    },
    yearsOfBritishRule: 211,
    basisForStartDate: "From cession by France, 1763",
    nameBeforeBritish: "Grenada, Windward Islands",
    splitUpAfterBritishLeft: "No - Carriacou and Petite Martinique included",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Strikes and killings around the date; Bishop's father shot January 1974",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Grenada",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "contested",
  },
  {
    slug: "guyana",
    name: "Guyana",
    region: "south-america",
    independence: { day: 26, month: 5, year: 1966, raw: "26 May 1966" },
    palette: {
      primary: "#009e49",
      secondary: "#fcd116",
      flagStops: ["#009e49", "#fcd116", "#ce1126"],
    },
    yearsOfBritishRule: 152,
    basisForStartDate: "From formal British cession, 1814",
    nameBeforeBritish: "British Guiana (Dutch before)",
    splitUpAfterBritishLeft: "Essequibo claimed by Venezuela",
    stillCommonwealthRealm: "No - republic 1970",
    unitedAfterIndependence: "Indo- and Afro-Guyanese split",
    violenceAtTransfer: "1962-64 racial violence, ~170 dead; UK suspended the constitution in 1953",
    sourceUrl: "https://en.wikipedia.org/wiki/Guyana_Independence_Act_1966",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "contested",
  },
  {
    slug: "india",
    name: "India",
    region: "asia",
    independence: { day: 15, month: 8, year: 1947, raw: "15 August 1947" },
    palette: {
      primary: "#ff9933",
      secondary: "#138808",
      flagStops: ["#ff9933", "#ffffff", "#138808"],
    },
    yearsOfBritishRule: 190,
    basisForStartDate: "From Plassey 1757; Crown rule 1858-1947 (89 yrs)",
    nameBeforeBritish: "Mughal empire and princely states",
    splitUpAfterBritishLeft: "Yes - partitioned into India and Pakistan",
    stillCommonwealthRealm: "No - republic 26 January 1950",
    unitedAfterIndependence: "565 princely states absorbed by 1949",
    violenceAtTransfer: "Yes - 200,000 to 2 million dead, 10-20 million displaced",
    sourceUrl: "https://en.wikipedia.org/wiki/Indian_Independence_Act_1947",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "iraq",
    name: "Iraq",
    region: "middle-east",
    independence: { day: 3, month: 10, year: 1932, raw: "3 October 1932" },
    palette: {
      primary: "#007a3d",
      secondary: "#ce1126",
      flagStops: ["#ce1126", "#ffffff", "#000000"],
    },
    yearsOfBritishRule: 15,
    basisForStartDate: "From British mandate, 1920",
    nameBeforeBritish: "Ottoman vilayets of Baghdad, Basra and Mosul",
    splitUpAfterBritishLeft: "No - three provinces welded into one",
    stillCommonwealthRealm: "No - monarchy to 1958, then republic",
    unitedAfterIndependence: "Held together only by force",
    violenceAtTransfer: "Yes - 1920 Iraqi revolt, ~10,000 dead, suppressed partly by RAF bombing",
    sourceUrl: "https://en.wikipedia.org/wiki/Mandatory_Iraq",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "ireland",
    name: "Ireland",
    region: "europe",
    independence: { day: 6, month: 12, year: 1922, raw: "6 December 1922 (republic 18 April 1949)", note: "republic 18 April 1949" },
    palette: {
      primary: "#169b62",
      secondary: "#ff883e",
      flagStops: ["#169b62", "#ffffff", "#ff883e"],
    },
    yearsOfBritishRule: 753,
    basisForStartDate: "From Norman invasion 1169; Act of Union 1801 (121 yrs)",
    nameBeforeBritish: "Kingdom of Ireland",
    splitUpAfterBritishLeft: "Yes - six counties remained in the UK",
    stillCommonwealthRealm: "No - left the Commonwealth 1949",
    unitedAfterIndependence: "No - partitioned, then civil war",
    violenceAtTransfer: "Yes - War of Independence 1919-21 (~2,000 dead), Irish Civil War 1922-23, Troubles 1968-98 (~3,500 dead)",
    sourceUrl: "https://en.wikipedia.org/wiki/Irish_Free_State",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "israel",
    name: "Israel",
    region: "middle-east",
    independence: { day: 14, month: 5, year: 1948, raw: "14 May 1948 (mandate expired 15 May)", note: "mandate expired 15 May" },
    palette: {
      primary: "#0038b8",
      secondary: "#6f9ede",
      flagStops: ["#0038b8", "#ffffff", "#0038b8"],
    },
    yearsOfBritishRule: 28,
    basisForStartDate: "From British occupation, 1917",
    nameBeforeBritish: "Mandatory Palestine",
    splitUpAfterBritishLeft: "Yes - UN partition plan; no Arab state emerged",
    stillCommonwealthRealm: "No",
    unitedAfterIndependence: "No - two-state plan collapsed into war",
    violenceAtTransfer: "Yes - 1947-49 war; ~700,000 Palestinians displaced (Nakba)",
    sourceUrl: "https://en.wikipedia.org/wiki/Israeli_Declaration_of_Independence",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "jamaica",
    name: "Jamaica",
    region: "caribbean",
    independence: { day: 6, month: 8, year: 1962, raw: "6 August 1962" },
    palette: {
      primary: "#009b3a",
      secondary: "#fed100",
      flagStops: ["#009b3a", "#fed100", "#000000"],
    },
    yearsOfBritishRule: 307,
    basisForStartDate: "From English capture from Spain, 1655",
    nameBeforeBritish: "Colony of Jamaica",
    splitUpAfterBritishLeft: "No, but the West Indies Federation collapsed",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Jamaica_Independence_Act_1962",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "jordan",
    name: "Jordan",
    region: "middle-east",
    independence: { day: 25, month: 5, year: 1946, raw: "25 May 1946" },
    palette: {
      primary: "#007a3d",
      secondary: "#ce1126",
      flagStops: ["#000000", "#ffffff", "#007a3d", "#ce1126"],
    },
    yearsOfBritishRule: 25,
    basisForStartDate: "From creation of Transjordan, 1921",
    nameBeforeBritish: "Emirate of Transjordan",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - Hashemite monarchy",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No - negotiated handover",
    sourceUrl: "https://en.wikipedia.org/wiki/Emirate_of_Transjordan",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "kenya",
    name: "Kenya",
    region: "africa",
    independence: { day: 12, month: 12, year: 1963, raw: "12 December 1963" },
    palette: {
      primary: "#006600",
      secondary: "#bb0000",
      flagStops: ["#000000", "#bb0000", "#006600"],
    },
    yearsOfBritishRule: 68,
    basisForStartDate: "From East Africa Protectorate, 1895",
    nameBeforeBritish: "Kenya Colony and Protectorate",
    splitUpAfterBritishLeft: "Northern Frontier District disputed with Somalia",
    stillCommonwealthRealm: "No - republic 1964; realm for one year",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Yes - Mau Mau Uprising 1952-60, 11,000+ dead, 150,000+ Kikuyu detained; UK paid compensation in 2013",
    sourceUrl: "https://en.wikipedia.org/wiki/Kenya_Independence_Act_1963",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "kiribati",
    name: "Kiribati",
    region: "oceania",
    independence: { day: 12, month: 7, year: 1979, raw: "12 July 1979" },
    palette: {
      primary: "#ce1126",
      secondary: "#003f87",
      flagStops: ["#ce1126", "#fcd116", "#003f87"],
    },
    yearsOfBritishRule: 87,
    basisForStartDate: "From protectorate, 1892",
    nameBeforeBritish: "Gilbert Islands",
    splitUpAfterBritishLeft: "Yes - separated from the Ellice Islands",
    stillCommonwealthRealm: "No - republic at independence",
    unitedAfterIndependence: "Banaba's grievance unresolved",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Kiribati",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "peaceful",
  },
  {
    slug: "lesotho",
    name: "Lesotho",
    region: "africa",
    independence: { day: 4, month: 10, year: 1966, raw: "4 October 1966" },
    palette: {
      primary: "#00209f",
      secondary: "#009543",
      flagStops: ["#00209f", "#ffffff", "#009543"],
    },
    yearsOfBritishRule: 98,
    basisForStartDate: "From British protection, 1868",
    nameBeforeBritish: "Basutoland",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - its own monarchy",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Lesotho_Independence_Act_1966",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "libya",
    name: "Libya",
    region: "africa",
    independence: { day: 24, month: 12, year: 1951, raw: "24 December 1951" },
    palette: {
      primary: "#239e46",
      secondary: "#e70013",
      flagStops: ["#e70013", "#000000", "#239e46"],
    },
    yearsOfBritishRule: 8,
    basisForStartDate: "British military administration from 1943",
    nameBeforeBritish: "Italian Libya",
    splitUpAfterBritishLeft: "No - three provinces federated",
    stillCommonwealthRealm: "No - monarchy to 1969",
    unitedAfterIndependence: "Federal kingdom, unified 1963",
    violenceAtTransfer: "No - UN-supervised transfer",
    sourceUrl: "https://en.wikipedia.org/wiki/Kingdom_of_Libya",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "malawi",
    name: "Malawi",
    region: "africa",
    independence: { day: 6, month: 7, year: 1964, raw: "6 July 1964" },
    palette: {
      primary: "#339e35",
      secondary: "#ce1126",
      flagStops: ["#000000", "#ce1126", "#339e35"],
    },
    yearsOfBritishRule: 73,
    basisForStartDate: "From protectorate, 1891",
    nameBeforeBritish: "Nyasaland",
    splitUpAfterBritishLeft: "Yes - left the Central African Federation (dissolved 31 Dec 1963)",
    stillCommonwealthRealm: "No - republic 1966",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "1959 state of emergency, 51 protesters killed",
    sourceUrl: "https://en.wikipedia.org/wiki/Malawi_Independence_Act_1964",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "contested",
  },
  {
    slug: "malaysia",
    name: "Malaysia",
    region: "asia",
    independence: { day: 31, month: 8, year: 1957, raw: "31 August 1957 (Malaysia formed 16 September 1963)", note: "Malaysia formed 16 September 1963" },
    palette: {
      primary: "#010066",
      secondary: "#ffcc00",
      flagStops: ["#cc0001", "#ffffff", "#010066", "#ffcc00"],
    },
    yearsOfBritishRule: 171,
    basisForStartDate: "From Penang, 1786",
    nameBeforeBritish: "Federated and Unfederated Malay States, Straits Settlements",
    splitUpAfterBritishLeft: "Yes - Singapore expelled 1965",
    stillCommonwealthRealm: "No - elects its own king every five years",
    unitedAfterIndependence: "Expanded in 1963, then shrank in 1965",
    violenceAtTransfer: "Yes - Malayan Emergency 1948-60, ~11,000 dead; 1969 race riots",
    sourceUrl: "https://en.wikipedia.org/wiki/Federation_of_Malaya_Independence_Act_1957",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "maldives",
    name: "Maldives",
    region: "asia",
    independence: { day: 26, month: 7, year: 1965, raw: "26 July 1965" },
    palette: {
      primary: "#d21034",
      secondary: "#007e3a",
      flagStops: ["#d21034", "#007e3a", "#ffffff"],
    },
    yearsOfBritishRule: 78,
    basisForStartDate: "From protectorate, 1887",
    nameBeforeBritish: "Maldive Islands",
    splitUpAfterBritishLeft: "Suvadive secession already crushed by 1963",
    stillCommonwealthRealm: "No - sultanate, then republic 1968",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No at transfer; British kept Gan airbase until 1976",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_the_Maldives",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "malta",
    name: "Malta",
    region: "europe",
    independence: { day: 21, month: 9, year: 1964, raw: "21 September 1964" },
    palette: {
      primary: "#cf142b",
      secondary: "#8a0f1d",
      flagStops: ["#ffffff", "#cf142b"],
    },
    yearsOfBritishRule: 164,
    basisForStartDate: "From British protection, 1800",
    nameBeforeBritish: "Crown Colony of Malta",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic 1974; realm 1964-74",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Malta_Independence_Act_1964",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "mauritius",
    name: "Mauritius",
    region: "africa",
    independence: { day: 12, month: 3, year: 1968, raw: "12 March 1968" },
    palette: {
      primary: "#1a206d",
      secondary: "#00a551",
      flagStops: ["#ea2839", "#1a206d", "#ffd500", "#00a551"],
    },
    yearsOfBritishRule: 158,
    basisForStartDate: "From British capture from France, 1810",
    nameBeforeBritish: "Isle de France (French)",
    splitUpAfterBritishLeft: "Yes - Chagos Archipelago detached in 1965, population expelled",
    stillCommonwealthRealm: "No - republic 1992; realm 1968-92",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Port Louis communal riots January 1968, ~25 dead",
    sourceUrl: "https://en.wikipedia.org/wiki/Mauritius_Independence_Act_1968",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "contested",
  },
  {
    slug: "myanmar",
    name: "Myanmar (Burma)",
    region: "asia",
    independence: { day: 4, month: 1, year: 1948, raw: "4 January 1948" },
    palette: {
      primary: "#34b233",
      secondary: "#ea2839",
      flagStops: ["#fecb00", "#34b233", "#ea2839"],
    },
    yearsOfBritishRule: 62,
    basisForStartDate: "From full annexation, 1886",
    nameBeforeBritish: "Burma (renamed Myanmar 1989)",
    splitUpAfterBritishLeft: "Ethnic states given secession rights that were never honoured",
    stillCommonwealthRealm: "No - left the Commonwealth entirely",
    unitedAfterIndependence: "No - civil war from year one",
    violenceAtTransfer: "Yes - Aung San assassinated July 1947; Karen insurgency from 1949, still ongoing",
    sourceUrl: "https://en.wikipedia.org/wiki/Burma_Independence_Act_1947",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "nauru",
    name: "Nauru",
    region: "oceania",
    independence: { day: 31, month: 1, year: 1968, raw: "31 January 1968" },
    palette: {
      primary: "#002b7f",
      secondary: "#ffc61e",
      flagStops: ["#002b7f", "#ffc61e", "#002b7f"],
    },
    yearsOfBritishRule: 54,
    basisForStartDate: "Australian administration from 1914 (German before)",
    nameBeforeBritish: "German Nauru",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Nauru_Independence_Act_1967",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    region: "oceania",
    independence: { day: 26, month: 9, year: 1907, raw: "26 September 1907 (Statute of Westminster adopted 1947)", note: "Statute of Westminster adopted 1947" },
    palette: {
      primary: "#00247d",
      secondary: "#cc142b",
      flagStops: ["#00247d", "#ffffff", "#cc142b"],
    },
    yearsOfBritishRule: 67,
    basisForStartDate: "From Treaty of Waitangi, 1840",
    nameBeforeBritish: "Colony of New Zealand",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No at transfer (New Zealand Wars 1845-72 earlier)",
    sourceUrl: "https://en.wikipedia.org/wiki/Dominion_of_New_Zealand",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "nigeria",
    name: "Nigeria",
    region: "africa",
    independence: { day: 1, month: 10, year: 1960, raw: "1 October 1960" },
    palette: {
      primary: "#008751",
      secondary: "#0f5c3c",
      flagStops: ["#008751", "#ffffff", "#008751"],
    },
    yearsOfBritishRule: 99,
    basisForStartDate: "From annexation of Lagos, 1861",
    nameBeforeBritish: "No single predecessor state",
    splitUpAfterBritishLeft: "No - amalgamated 1914, stayed whole",
    stillCommonwealthRealm: "No - republic 1963",
    unitedAfterIndependence: "Federal, and it nearly broke",
    violenceAtTransfer: "Peaceful exit; Biafran war 1967-70 killed 1-3 million",
    sourceUrl: "https://en.wikipedia.org/wiki/Nigeria_Independence_Act_1960",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "contested",
  },
  {
    slug: "oman",
    name: "Oman",
    region: "middle-east",
    independence: { year: 1951, raw: "1951 Treaty of Friendship (British representatives left 1971)", note: "British representatives left 1971" },
    palette: {
      primary: "#db161b",
      secondary: "#008000",
      flagStops: ["#ffffff", "#db161b", "#008000"],
    },
    yearsOfBritishRule: 60,
    basisForStartDate: "British influence from 1891 agreement",
    nameBeforeBritish: "Sultanate of Muscat and Oman",
    splitUpAfterBritishLeft: "Zanzibar split off in 1856",
    stillCommonwealthRealm: "No - its own sultanate",
    unitedAfterIndependence: "Interior imamate suppressed",
    violenceAtTransfer: "Yes - Jebel Akhdar War 1954-59 and Dhofar Rebellion 1962-76, both with British forces",
    sourceUrl: "https://en.wikipedia.org/wiki/Muscat_and_Oman",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "pakistan",
    name: "Pakistan",
    region: "asia",
    independence: { day: 14, month: 8, year: 1947, raw: "14 August 1947" },
    palette: {
      primary: "#01411c",
      secondary: "#4b8f6f",
      flagStops: ["#ffffff", "#01411c"],
    },
    yearsOfBritishRule: 190,
    basisForStartDate: "Same basis as India",
    nameBeforeBritish: "Punjab, Sindh, NWFP, Balochistan, Bengal",
    splitUpAfterBritishLeft: "Yes - created by partition, then split again in 1971",
    stillCommonwealthRealm: "No - republic 1956",
    unitedAfterIndependence: "No - two wings 1,600 km apart",
    violenceAtTransfer: "Yes - Partition violence and first Kashmir war within 10 weeks",
    sourceUrl: "https://en.wikipedia.org/wiki/Dominion_of_Pakistan",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "papua-new-guinea",
    name: "Papua New Guinea",
    region: "oceania",
    independence: { day: 16, month: 9, year: 1975, raw: "16 September 1975" },
    palette: {
      primary: "#ce1126",
      secondary: "#fcd116",
      flagStops: ["#ce1126", "#000000", "#fcd116"],
    },
    yearsOfBritishRule: 91,
    basisForStartDate: "British New Guinea 1884, Australian from 1906",
    nameBeforeBritish: "Papua and New Guinea",
    splitUpAfterBritishLeft: "Bougainville still unresolved",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Bougainville nearly left",
    violenceAtTransfer: "No at transfer; Bougainville civil war 1988-98, up to 20,000 dead",
    sourceUrl: "https://en.wikipedia.org/wiki/Papua_New_Guinea_Independence_Act_1975",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "qatar",
    name: "Qatar",
    region: "middle-east",
    independence: { day: 3, month: 9, year: 1971, raw: "3 September 1971" },
    palette: {
      primary: "#8a1538",
      secondary: "#5c0e25",
      flagStops: ["#ffffff", "#8a1538"],
    },
    yearsOfBritishRule: 55,
    basisForStartDate: "From treaty, 1916",
    nameBeforeBritish: "British Protectorate of Qatar",
    splitUpAfterBritishLeft: "Yes - walked out of the nine-state federation",
    stillCommonwealthRealm: "No - emirate",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Qatar",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "peaceful",
  },
  {
    slug: "saint-kitts-and-nevis",
    name: "Saint Kitts and Nevis",
    region: "caribbean",
    independence: { day: 19, month: 9, year: 1983, raw: "19 September 1983" },
    palette: {
      primary: "#009e49",
      secondary: "#fcd116",
      flagStops: ["#009e49", "#fcd116", "#ce1126", "#000000"],
    },
    yearsOfBritishRule: 360,
    basisForStartDate: "From English settlement, 1623",
    nameBeforeBritish: "Saint Christopher-Nevis-Anguilla",
    splitUpAfterBritishLeft: "Yes - Anguilla broke away in 1967 and returned to British rule",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Nevis retains a constitutional right to secede",
    violenceAtTransfer: "Anguilla crisis; British paratroopers landed 1969, no deaths",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Saint_Kitts_and_Nevis",
    isCommonwealthRealm: true,
    wasPartitioned: true,
    transferCharacter: "contested",
  },
  {
    slug: "saint-lucia",
    name: "Saint Lucia",
    region: "caribbean",
    independence: { day: 22, month: 2, year: 1979, raw: "22 February 1979" },
    palette: {
      primary: "#66ccff",
      secondary: "#fcd116",
      flagStops: ["#66ccff", "#ffffff", "#000000", "#fcd116"],
    },
    yearsOfBritishRule: 165,
    basisForStartDate: "From final British possession, 1814",
    nameBeforeBritish: "Saint Lucia, Windward Islands",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Saint_Lucia",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "saint-vincent-and-the-grenadines",
    name: "Saint Vincent and the Grenadines",
    region: "caribbean",
    independence: { day: 27, month: 10, year: 1979, raw: "27 October 1979" },
    palette: {
      primary: "#0072c6",
      secondary: "#fcd116",
      flagStops: ["#0072c6", "#fcd116", "#009e60"],
    },
    yearsOfBritishRule: 216,
    basisForStartDate: "From cession by France, 1763",
    nameBeforeBritish: "Saint Vincent, Windward Islands",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Union Island uprising December 1979, weeks after independence",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Saint_Vincent_and_the_Grenadines",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "contested",
  },
  {
    slug: "samoa",
    name: "Samoa",
    region: "oceania",
    independence: { day: 1, month: 1, year: 1962, raw: "1 January 1962" },
    palette: {
      primary: "#002b7f",
      secondary: "#ce1126",
      flagStops: ["#ce1126", "#002b7f", "#ffffff"],
    },
    yearsOfBritishRule: 48,
    basisForStartDate: "New Zealand administration from 1914 (German before)",
    nameBeforeBritish: "German Samoa",
    splitUpAfterBritishLeft: "Yes - American Samoa remained separate",
    stillCommonwealthRealm: "No - own paramount chiefs as head of state",
    unitedAfterIndependence: "No - divided from American Samoa since 1899",
    violenceAtTransfer: "Black Saturday 1929: NZ police shot 11 Mau demonstrators",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Samoa",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "contested",
  },
  {
    slug: "seychelles",
    name: "Seychelles",
    region: "africa",
    independence: { day: 29, month: 6, year: 1976, raw: "29 June 1976" },
    palette: {
      primary: "#003f87",
      secondary: "#fcd856",
      flagStops: ["#003f87", "#fcd856", "#d62828", "#007a3d"],
    },
    yearsOfBritishRule: 162,
    basisForStartDate: "From formal British cession, 1814",
    nameBeforeBritish: "French Sechelles",
    splitUpAfterBritishLeft: "Aldabra group returned from BIOT at independence",
    stillCommonwealthRealm: "No - republic at independence",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No at transfer; coup in 1977",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Seychelles",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "sierra-leone",
    name: "Sierra Leone",
    region: "africa",
    independence: { day: 27, month: 4, year: 1961, raw: "27 April 1961" },
    palette: {
      primary: "#1eb53a",
      secondary: "#0072c6",
      flagStops: ["#1eb53a", "#ffffff", "#0072c6"],
    },
    yearsOfBritishRule: 153,
    basisForStartDate: "From Crown colony, 1808",
    nameBeforeBritish: "Sierra Leone Colony and Protectorate",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic 1971",
    unitedAfterIndependence: "Freetown Krio elite vs. protectorate interior",
    violenceAtTransfer: "No - orderly transfer",
    sourceUrl: "https://en.wikipedia.org/wiki/Sierra_Leone_Independence_Act_1961",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "singapore",
    name: "Singapore",
    region: "asia",
    independence: { day: 9, month: 8, year: 1965, raw: "31 August 1963 from Britain; 9 August 1965 from Malaysia" },
    palette: {
      primary: "#ef3340",
      secondary: "#9c1f28",
      flagStops: ["#ef3340", "#ffffff"],
    },
    yearsOfBritishRule: 146,
    basisForStartDate: "From founding of the port, 1819",
    nameBeforeBritish: "Crown Colony of Singapore",
    splitUpAfterBritishLeft: "Yes - expelled from Malaysia",
    stillCommonwealthRealm: "No - republic",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "1964 race riots killed 36",
    sourceUrl: "https://en.wikipedia.org/wiki/Proclamation_of_Singapore",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "contested",
  },
  {
    slug: "solomon-islands",
    name: "Solomon Islands",
    region: "oceania",
    independence: { day: 7, month: 7, year: 1978, raw: "7 July 1978" },
    palette: {
      primary: "#0051ba",
      secondary: "#215b33",
      flagStops: ["#0051ba", "#fcd116", "#215b33"],
    },
    yearsOfBritishRule: 85,
    basisForStartDate: "From protectorate, 1893",
    nameBeforeBritish: "British Solomon Islands Protectorate",
    splitUpAfterBritishLeft: "Northern Solomons stayed with PNG",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Guadalcanal/Malaita tensions 1998-2003",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Solomon_Islands_Act_1978",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "somalia",
    name: "Somalia",
    region: "africa",
    independence: { day: 26, month: 6, year: 1960, raw: "26 June 1960 (union with Italian Somaliland 1 July 1960)", note: "union with Italian Somaliland 1 July 1960" },
    palette: {
      primary: "#4189dd",
      secondary: "#1c5a99",
      flagStops: ["#4189dd", "#ffffff", "#4189dd"],
    },
    yearsOfBritishRule: 76,
    basisForStartDate: "From Somaliland protectorate, 1884",
    nameBeforeBritish: "British Somaliland",
    splitUpAfterBritishLeft: "Somaliland re-declared independence in 1991",
    stillCommonwealthRealm: "No - republic",
    unitedAfterIndependence: "Merged with Italian Somaliland, then collapsed",
    violenceAtTransfer: "No - peaceful transfer",
    sourceUrl: "https://en.wikipedia.org/wiki/British_Somaliland",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "south-africa",
    name: "South Africa",
    region: "africa",
    independence: { day: 31, month: 5, year: 1910, raw: "31 May 1910 (republic 31 May 1961)", note: "republic 31 May 1961" },
    palette: {
      primary: "#007a4d",
      secondary: "#ffb612",
      flagStops: ["#de3831", "#ffffff", "#007a4d", "#ffb612", "#002395"],
    },
    yearsOfBritishRule: 104,
    basisForStartDate: "From British capture of the Cape, 1806",
    nameBeforeBritish: "Cape Colony, Natal, Transvaal, Orange Free State",
    splitUpAfterBritishLeft: "No - four colonies fused",
    stillCommonwealthRealm: "No - republic since 1961",
    unitedAfterIndependence: "United on paper, segregated in law",
    violenceAtTransfer: "Second Boer War 1899-1902 preceded it, ~75,000 dead incl. ~28,000 Boer and ~20,000 African civilians in camps",
    sourceUrl: "https://en.wikipedia.org/wiki/Union_of_South_Africa",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "contested",
  },
  {
    slug: "south-yemen",
    name: "South Yemen",
    region: "middle-east",
    independence: { day: 30, month: 11, year: 1967, raw: "30 November 1967" },
    palette: {
      primary: "#0080c0",
      secondary: "#ce1126",
      flagStops: ["#ce1126", "#ffffff", "#000000", "#0080c0"],
    },
    yearsOfBritishRule: 128,
    basisForStartDate: "From capture of Aden, 1839",
    nameBeforeBritish: "Aden Colony and Protectorate of South Arabia",
    splitUpAfterBritishLeft: "Yes - North and South Yemen kept apart",
    stillCommonwealthRealm: "No - Marxist republic",
    unitedAfterIndependence: "No - united with the North only in 1990",
    violenceAtTransfer: "Yes - Aden Emergency 1963-67, ~2,000 dead",
    sourceUrl: "https://en.wikipedia.org/wiki/People%27s_Democratic_Republic_of_Yemen",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
  {
    slug: "sri-lanka",
    name: "Sri Lanka",
    region: "asia",
    independence: { day: 4, month: 2, year: 1948, raw: "4 February 1948" },
    palette: {
      primary: "#8d2029",
      secondary: "#ffbe29",
      flagStops: ["#eb7400", "#00534e", "#8d2029", "#ffbe29"],
    },
    yearsOfBritishRule: 133,
    basisForStartDate: "From Kandyan Convention, 1815 (coast from 1796)",
    nameBeforeBritish: "Ceylon (renamed Sri Lanka 1972)",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic 1972; realm 1948-72",
    unitedAfterIndependence: "Yes - whole island as one state",
    violenceAtTransfer: "No at transfer; civil war 1983-2009 killed 80,000-100,000",
    sourceUrl: "https://en.wikipedia.org/wiki/Ceylon_Independence_Act_1947",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "sudan",
    name: "Sudan",
    region: "africa",
    independence: { day: 1, month: 1, year: 1956, raw: "1 January 1956" },
    palette: {
      primary: "#007229",
      secondary: "#d21034",
      flagStops: ["#d21034", "#ffffff", "#000000", "#007229"],
    },
    yearsOfBritishRule: 57,
    basisForStartDate: "From Anglo-Egyptian reconquest, 1899",
    nameBeforeBritish: "Anglo-Egyptian Sudan",
    splitUpAfterBritishLeft: "South Sudan seceded in 2011",
    stillCommonwealthRealm: "No - republic at independence",
    unitedAfterIndependence: "No - civil war began before independence",
    violenceAtTransfer: "Yes - Torit mutiny August 1955, four months before independence",
    sourceUrl: "https://en.wikipedia.org/wiki/Anglo-Egyptian_Sudan",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "tanzania",
    name: "Tanzania",
    region: "africa",
    independence: { day: 9, month: 12, year: 1961, raw: "9 December 1961 (Zanzibar 10 December 1963; union 26 April 1964)", note: "Zanzibar 10 December 1963; union 26 April 1964" },
    palette: {
      primary: "#1eb53a",
      secondary: "#00a3dd",
      flagStops: ["#1eb53a", "#fcd116", "#000000", "#00a3dd"],
    },
    yearsOfBritishRule: 42,
    basisForStartDate: "British mandate from 1919 (German before); Zanzibar from 1890",
    nameBeforeBritish: "Tanganyika and Zanzibar",
    splitUpAfterBritishLeft: "No - a merger, not a split",
    stillCommonwealthRealm: "No - republic 1962",
    unitedAfterIndependence: "Yes - united as Tanzania 26 April 1964",
    violenceAtTransfer: "Zanzibar Revolution January 1964 killed thousands of Arab and South Asian islanders",
    sourceUrl: "https://en.wikipedia.org/wiki/Tanganyika_Independence_Act_1961",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "contested",
  },
  {
    slug: "bahamas",
    name: "The Bahamas",
    region: "caribbean",
    independence: { day: 10, month: 7, year: 1973, raw: "10 July 1973" },
    palette: {
      primary: "#00778b",
      secondary: "#ffc72c",
      flagStops: ["#00778b", "#ffc72c", "#000000"],
    },
    yearsOfBritishRule: 255,
    basisForStartDate: "From Crown colony status, 1718",
    nameBeforeBritish: "British Bahamas",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Bahamas_Independence_Act_1973",
    isCommonwealthRealm: true,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "gambia",
    name: "The Gambia",
    region: "africa",
    independence: { day: 18, month: 2, year: 1965, raw: "18 February 1965" },
    palette: {
      primary: "#3a7728",
      secondary: "#0c1c8c",
      flagStops: ["#ce1126", "#0c1c8c", "#3a7728"],
    },
    yearsOfBritishRule: 144,
    basisForStartDate: "From Bathurst settlement, 1821",
    nameBeforeBritish: "Gambia Colony and Protectorate",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - republic 1970; realm 1965-70",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Gambia_Independence_Act_1964",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "tonga",
    name: "Tonga",
    region: "oceania",
    independence: { day: 4, month: 6, year: 1970, raw: "4 June 1970" },
    palette: {
      primary: "#c10000",
      secondary: "#7d0000",
      flagStops: ["#c10000", "#ffffff", "#c10000"],
    },
    yearsOfBritishRule: 70,
    basisForStartDate: "From Treaty of Friendship, 1900",
    nameBeforeBritish: "Kingdom of Tonga",
    splitUpAfterBritishLeft: "No",
    stillCommonwealthRealm: "No - its own monarchy, never broken",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No - never colonised",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Tonga",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "trinidad-and-tobago",
    name: "Trinidad and Tobago",
    region: "caribbean",
    independence: { day: 31, month: 8, year: 1962, raw: "31 August 1962" },
    palette: {
      primary: "#ce1126",
      secondary: "#1b1d21",
      flagStops: ["#ce1126", "#ffffff", "#000000"],
    },
    yearsOfBritishRule: 160,
    basisForStartDate: "From cession of Trinidad, 1802",
    nameBeforeBritish: "Trinidad and Tobago (joined administratively 1889)",
    splitUpAfterBritishLeft: "No - two islands, one state",
    stillCommonwealthRealm: "No - republic 1976; realm 1962-76",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No",
    sourceUrl: "https://en.wikipedia.org/wiki/Trinidad_and_Tobago_Independence_Act_1962",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "tuvalu",
    name: "Tuvalu",
    region: "oceania",
    independence: { day: 1, month: 10, year: 1978, raw: "1 October 1978" },
    palette: {
      primary: "#418fde",
      secondary: "#ffce00",
      flagStops: ["#418fde", "#ffce00", "#ffffff"],
    },
    yearsOfBritishRule: 86,
    basisForStartDate: "From protectorate, 1892",
    nameBeforeBritish: "Ellice Islands (Gilbert and Ellice Islands Colony)",
    splitUpAfterBritishLeft: "Yes - separated from the Gilberts by 1974 referendum",
    stillCommonwealthRealm: "Yes",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No - a consensual separation",
    sourceUrl: "https://en.wikipedia.org/wiki/History_of_Tuvalu",
    isCommonwealthRealm: true,
    wasPartitioned: true,
    transferCharacter: "peaceful",
  },
  {
    slug: "uganda",
    name: "Uganda",
    region: "africa",
    independence: { day: 9, month: 10, year: 1962, raw: "9 October 1962" },
    palette: {
      primary: "#fcdc04",
      secondary: "#d90000",
      flagStops: ["#000000", "#fcdc04", "#d90000"],
    },
    yearsOfBritishRule: 68,
    basisForStartDate: "From protectorate, 1894",
    nameBeforeBritish: "Uganda Protectorate",
    splitUpAfterBritishLeft: "No, but Buganda held special status",
    stillCommonwealthRealm: "No - republic 1963",
    unitedAfterIndependence: "Federal fudge that failed by 1966",
    violenceAtTransfer: "No - peaceful transfer",
    sourceUrl: "https://en.wikipedia.org/wiki/Uganda_Independence_Act_1962",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "united-arab-emirates",
    name: "United Arab Emirates",
    region: "middle-east",
    independence: { day: 2, month: 12, year: 1971, raw: "2 December 1971 (Ras Al Khaimah joined 10 February 1972)", note: "Ras Al Khaimah joined 10 February 1972" },
    palette: {
      primary: "#00732f",
      secondary: "#c8102e",
      flagStops: ["#00732f", "#ffffff", "#000000", "#ff0000"],
    },
    yearsOfBritishRule: 151,
    basisForStartDate: "From General Maritime Treaty, 1820",
    nameBeforeBritish: "Trucial States / Trucial Oman",
    splitUpAfterBritishLeft: "No - a federation, not a partition",
    stillCommonwealthRealm: "No - federal monarchy",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "No; Iran seized Abu Musa and the Tunbs on 30 November 1971",
    sourceUrl: "https://en.wikipedia.org/wiki/Trucial_States",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "peaceful",
  },
  {
    slug: "united-states",
    name: "United States",
    region: "north-america",
    independence: { day: 4, month: 7, year: 1776, raw: "4 July 1776 (recognised 3 September 1783)", note: "recognised 3 September 1783" },
    palette: {
      primary: "#3c3b6e",
      secondary: "#b22234",
      flagStops: ["#b22234", "#ffffff", "#3c3b6e"],
    },
    yearsOfBritishRule: 169,
    basisForStartDate: "From Jamestown, 1607",
    nameBeforeBritish: "Thirteen Colonies",
    splitUpAfterBritishLeft: "Partly - Loyalist north remained British",
    stillCommonwealthRealm: "No",
    unitedAfterIndependence: "Yes - 13 colonies federated",
    violenceAtTransfer: "Yes - Revolutionary War 1775-83, ~25,000 American dead, ~60,000 Loyalists exiled",
    sourceUrl: "https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "vanuatu",
    name: "Vanuatu",
    region: "oceania",
    independence: { day: 30, month: 7, year: 1980, raw: "30 July 1980" },
    palette: {
      primary: "#009543",
      secondary: "#fdce12",
      flagStops: ["#d21034", "#009543", "#000000", "#fdce12"],
    },
    yearsOfBritishRule: 74,
    basisForStartDate: "Anglo-French condominium from 1906",
    nameBeforeBritish: "New Hebrides",
    splitUpAfterBritishLeft: "Santo secession defeated",
    stillCommonwealthRealm: "No - republic",
    unitedAfterIndependence: "Anglophone/francophone split persists",
    violenceAtTransfer: "Yes - Santo Rebellion (Coconut War) 1980",
    sourceUrl: "https://en.wikipedia.org/wiki/New_Hebrides",
    isCommonwealthRealm: false,
    wasPartitioned: false,
    transferCharacter: "violent",
  },
  {
    slug: "zambia",
    name: "Zambia",
    region: "africa",
    independence: { day: 24, month: 10, year: 1964, raw: "24 October 1964" },
    palette: {
      primary: "#198a00",
      secondary: "#ef7d00",
      flagStops: ["#198a00", "#ef7d00", "#000000", "#de2010"],
    },
    yearsOfBritishRule: 73,
    basisForStartDate: "From protectorate, 1891",
    nameBeforeBritish: "Northern Rhodesia",
    splitUpAfterBritishLeft: "Yes - left the Central African Federation",
    stillCommonwealthRealm: "No - republic at independence",
    unitedAfterIndependence: "Yes",
    violenceAtTransfer: "Lumpa Church uprising July-October 1964, ~700 dead",
    sourceUrl: "https://en.wikipedia.org/wiki/Zambia_Independence_Act_1964",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "contested",
  },
  {
    slug: "zimbabwe",
    name: "Zimbabwe",
    region: "africa",
    independence: { day: 18, month: 4, year: 1980, raw: "18 April 1980" },
    palette: {
      primary: "#319208",
      secondary: "#ffd200",
      flagStops: ["#319208", "#ffd200", "#de2010", "#000000"],
    },
    yearsOfBritishRule: 90,
    basisForStartDate: "From BSAC occupation, 1890",
    nameBeforeBritish: "Southern Rhodesia / Rhodesia (UDI 1965)",
    splitUpAfterBritishLeft: "Yes - left the Central African Federation 1963",
    stillCommonwealthRealm: "No - republic at independence",
    unitedAfterIndependence: "Shona/Ndebele split, then Gukurahundi",
    violenceAtTransfer: "Yes - Rhodesian Bush War 1964-79, 20,000+ dead; Gukurahundi 1983-87, ~20,000 Ndebele",
    sourceUrl: "https://en.wikipedia.org/wiki/Lancaster_House_Agreement",
    isCommonwealthRealm: false,
    wasPartitioned: true,
    transferCharacter: "violent",
  },
];
